services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      POSGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocketlog
      
    
    